version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data: